### ISSUE TITLE
Xeno weapons have inconsistent max limit breaks

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#250]
As seen:
![image](https://user-images.githubusercontent.com/1794735/224528525-fea29c95-c48a-4d20-b59b-401b098121cf.png)

All forged xeno weapons can go to 5* in the game

**Comment by jedmund** [comment]
Thanks, this is a combination of me missing some and the wiki being inconsistent with what technically has a limit break and what doesn't.

This has been updated in production so that:
* Unforged weapons can only go to MLB
* All forged weapons can go to ULB

Please reopen this issue if something still doesn't look right!
