### ISSUE TITLE
Ultimate Mastery skills are not available in the Job Skill picker

### ISSUE THREAD

**Issue by Vazkii** [jedmund/hensei-web#251]
![image](https://user-images.githubusercontent.com/1794735/225054675-8dda99c7-2833-4418-8a2c-2215c1e0ca1e.png)

**Comment by jedmund** [comment]
These are available now! I forgot to add them when I updated content the other day (which I still need to update on the Updates page)

A note: The skills dialog does not seem to paginate some requests, so it caps at 10 entries. For many of the new classes, this means that if you select `Extended Mastery` from the dropdown, you won't see all the available skills. If you search for them, they will show up. This will be fixed in a future update and is being tracked in #258.
